ARG ASROOT

ARG FEATURE_HAS_MY_USER_UID
ARG FEATURE_HAS_MY_USER_GID
ARG FEATURE_HAS_MY_USER_NAME
ARG FEATURE_HAS_MY_USER_GECOS

ENV FEATURE_HAS_MY_USER_UID=$FEATURE_HAS_MY_USER_UID
ENV FEATURE_HAS_MY_USER_GID=$FEATURE_HAS_MY_USER_GID
ENV FEATURE_HAS_MY_USER_NAME=$FEATURE_HAS_MY_USER_NAME
ENV FEATURE_HAS_MY_USER_GECOS=$FEATURE_HAS_MY_USER_GECOS

RUN $ASROOT apt-get install -y sudo
COPY embed_me.sh /
RUN $ASROOT chmod 775 /embed_me.sh
RUN $ASROOT /embed_me.sh
RUN $ASROOT rm /embed_me.sh
