RUN echo "#!/bin/bash" > /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "echo PRETEND THIS IS A COMMAND RUNNING" >> /myinit.sh
RUN echo "/myshutdown" >> /myinit.sh
RUN chmod 755 /myinit.sh
COPY myshutdown /
