ARG ASROOT
ARG FEATURE_HAS_MY_USER_NAME

ENV FEATURE_HAS_MY_USER_NAME=$FEATURE_HAS_MY_USER_NAME
ENV HOME /home/$FEATURE_HAS_MY_USER_NAME

RUN $ASROOT apt-get install -y kmod

COPY uml.sh /
RUN $ASROOT chmod 755 /uml.sh
